
const grid=document.querySelector('#grid'),movesEl=document.querySelector('#moves'),pairsEl=document.querySelector('#pairs'),finish=document.querySelector('#finishCard');
const cakes=[['#ff8175','#ffe8d9','★'],['#62beb8','#fff0c7','●'],['#f5bd3f','#fff2c8','✦'],['#7969b0','#e9e2ff','◆'],['#59b996','#e2f4e8','♣'],['#d77a9b','#ffe2ec','♥']];
let first=null,lock=false,moves=0,pairs=0,cards=[];
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function cakeSvg(c1,c2,sym){return `<svg viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg"><circle cx="50" cy="27" r="13" fill="${c2}" stroke="${c1}" stroke-width="4"/><text x="50" y="34" text-anchor="middle" font-size="18" fill="${c1}">${sym}</text><path d="M23 59c0-11 8-19 19-19h16c11 0 19 8 19 19v6H23z" fill="${c2}"/><path d="M19 63h62l-7 24H26z" fill="${c1}"/><path d="M28 72h44" stroke="rgba(255,255,255,.7)" stroke-width="5" stroke-linecap="round"/></svg>`}
function init(){grid.innerHTML='';first=null;lock=false;moves=0;pairs=0;movesEl.textContent='0';pairsEl.textContent='0';finish.classList.remove('show');cards=shuffle(cakes.flatMap((c,i)=>[{key:i,c},{key:i,c}]));cards.forEach((it,idx)=>{const b=document.createElement('button');b.className='memory-card';b.dataset.key=it.key;b.innerHTML=`<span class="memory-back">✦</span><span class="memory-front">${cakeSvg(...it.c)}</span>`;grid.appendChild(b)})}
grid.addEventListener('click',e=>{const c=e.target.closest('.memory-card');if(!c||lock||c.classList.contains('open')||c.classList.contains('matched'))return;c.classList.add('open');if(!first){first=c;return}moves++;movesEl.textContent=moves;if(first.dataset.key===c.dataset.key){first.classList.remove('open');c.classList.remove('open');first.classList.add('matched');c.classList.add('matched');first=null;pairs++;pairsEl.textContent=pairs;if(pairs===6){finish.classList.add('show');Site.win('Все пары найдены! ✦')}}else{lock=true;const a=first;first=null;setTimeout(()=>{a.classList.remove('open');c.classList.remove('open');lock=false},800)}});
document.querySelector('#restart').onclick=init;init();
